name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . \
           --file greeter/Dockerfile \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }} \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
        
    - name: Push the Docker images
      run: |
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
        docker push ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push ghcr.io/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
