name: Docker Image CI

on:
  push:
    tags: 
      # official semver regex (https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string)
      - '^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . \
           --file greeter/Dockerfile \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }} \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
        
    - name: Push the Docker images
      run: |
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
        docker push ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push ghcr.io/francescoilario/gcr-trial/greeter:${{ github.event.release.tag_name }}
