name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login on Github
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u FrancescoIlario --password-stdin
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u FrancescoIlario --password-stdin
    - name: Build the Docker image
      run: |
        docker build greeter/ \
           --file greeter/Dockerfile \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD) \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD) \
           --tag ghcr.io/francescoilario/gcr-trial/greeter:$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)
    - name: Push the Docker images
      run: |
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push docker.pkg.github.com/francescoilario/gcr-trial/greeter:$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)
        docker push ghcr.io/francescoilario/gcr-trial/greeter:$(git rev-parse --short HEAD)
        docker push ghcr.io/francescoilario/gcr-trial/greeter:$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)
